---
packages:
  - internal/*
  - internal/lint-configs/*
  - packages/*
  - packages/@core/base/*
  - scripts/*
  - apps/*
catalog:
  '@changesets/cli': ^2.27.9
  '@changesets/git': ^3.0.1
  '@clack/prompts': ^0.7.0
  '@commitlint/cli': ^19.5.0
  '@commitlint/config-conventional': ^19.5.0
  '@eslint/js': ^9.13.0
  '@iconify/json': ^2.2.264
  '@iconify/tailwind': ^1.1.3
  '@iconify/vue': ^4.1.2
  '@intlify/core-base': ^10.0.4
  '@intlify/unplugin-vue-i18n': ^5.2.0
  '@jspm/generator': ^2.4.1
  '@manypkg/get-packages': ^2.2.2
  '@pnpm/workspace.read-manifest': ^2.2.1
  '@stylistic/stylelint-plugin': ^3.1.1
  '@types/archiver': ^6.0.3
  '@types/eslint': ^9.6.1
  '@types/html-minifier-terser': ^7.0.2
  '@types/node': ^22.8.1
  '@types/postcss-import': ^14.0.3
  '@typescript-eslint/eslint-plugin': ^8.11.0
  '@typescript-eslint/parser': ^8.11.0
  '@vitejs/plugin-vue': ^5.2.1
  '@vitejs/plugin-vue-jsx': ^4.0.1
  '@vue/tsconfig': ^0.7.0
  archiver: ^7.0.1
  autoprefixer: ^10.4.20
  cac: ^6.7.14
  chalk: ^5.3.0
  cheerio: 1.0.0
  circular-dependency-scanner: ^2.3.0
  consola: ^3.2.3
  cross-env: ^7.0.3
  cssnano: ^7.0.6
  dayjs: ^1.11.13
  depcheck: ^1.4.7
  dotenv: ^16.4.5
  eslint: ^9.13.0
  eslint-config-turbo: ^2.2.3
  eslint-plugin-command: ^0.2.6
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-import-x: ^4.3.1
  eslint-plugin-jsdoc: ^50.4.3
  eslint-plugin-jsonc: ^2.16.0
  eslint-plugin-n: ^17.11.1
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^3.9.1
  eslint-plugin-prettier: ^5.2.1
  eslint-plugin-regexp: ^2.6.0
  eslint-plugin-unicorn: ^56.0.0
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vitest: ^0.5.4
  eslint-plugin-vue: ^9.29.1
  execa: ^9.5.0
  find-up: ^7.0.0
  get-port: ^7.1.0
  globals: ^15.11.0
  html-minifier-terser: ^7.2.0
  husky: ^9.1.6
  jsonc-eslint-parser: ^2.4.0
  lint-staged: ^15.2.10
  nanoid: ^5.0.7
  nitropack: ^2.9.7
  nprogress: ^0.2.0
  ora: ^8.1.0
  pkg-types: ^1.2.1
  postcss: ^8.4.47
  postcss-antd-fixes: ^0.2.0
  postcss-html: ^1.7.0
  postcss-import: ^16.1.0
  postcss-preset-env: ^10.0.8
  postcss-scss: ^4.0.9
  prettier: ^3.3.3
  prettier-plugin-tailwindcss: ^0.6.8
  publint: ^0.2.12
  resolve.exports: ^2.0.2
  rimraf: ^6.0.1
  rollup: ^4.24.1
  rollup-plugin-visualizer: ^5.12.0
  sass: 1.79.5
  stylelint: ^16.10.0
  stylelint-config-recess-order: ^5.1.1
  stylelint-config-recommended: ^14.0.1
  stylelint-config-recommended-scss: ^14.1.0
  stylelint-config-recommended-vue: ^1.5.0
  stylelint-config-standard: ^36.0.1
  stylelint-order: ^6.0.4
  stylelint-prettier: ^5.0.2
  stylelint-scss: ^6.8.1
  tailwind-merge: ^2.5.4
  tailwindcss: ^3.4.14
  tailwindcss-animate: ^1.0.7
  turbo: ^2.2.3
  typescript: ~5.6.2
  unbuild: ^2.0.0
  vite: ^5.4.10
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: ^4.5.0
  vite-plugin-html: ^3.2.2
  vite-plugin-lazy-import: ^1.0.7
  vite-plugin-lib-inject-css: ^2.1.1
  vite-plugin-pwa: ^0.20.5
  vite-plugin-vue-devtools: ^7.5.4
  vue: ^3.5.13
  vue-eslint-parser: ^9.4.3
  vue-tsc: ^2.2.0
